//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turism
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtractieTuristica
    {
        public AtractieTuristica()
        {
            this.Comentarius = new HashSet<Comentariu>();
        }
    
        public int ID { get; set; }
        public string Denumire { get; set; }
        public string Descriere { get; set; }
        public string WebSite { get; set; }
        public string Adresa { get; set; }
        public Nullable<double> Longitudine { get; set; }
        public Nullable<double> Latitudine { get; set; }
        public Nullable<int> IdOras { get; set; }
        public string Orar { get; set; }
    
        public virtual Ora Ora { get; set; }
        public virtual ICollection<Comentariu> Comentarius { get; set; }
    }
}
