//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turism
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camera
    {
        public int ID { get; set; }
        public Nullable<int> IdHotel { get; set; }
        public Nullable<int> NrPaturi { get; set; }
        public string TipPat { get; set; }
        public Nullable<double> Pret { get; set; }
        public string Detalii { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
