//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turism
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Comandas = new HashSet<Comanda>();
        }
    
        public int ID { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string CNP { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DataInceputCazare { get; set; }
        public Nullable<System.DateTime> DataSfarsitCazare { get; set; }
    
        public virtual ICollection<Comanda> Comandas { get; set; }
    }
}
