//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turism
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comanda
    {
        public int ID { get; set; }
        public Nullable<int> IdOferta { get; set; }
        public Nullable<int> IdClient { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual OfertaSejur OfertaSejur { get; set; }
    }
}
