//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turism
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itinerariu
    {
        public int ID { get; set; }
        public string Descriere { get; set; }
        public string Orar { get; set; }
    }
}
