//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turism
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TurismBD : DbContext
    {
        public TurismBD()
            : base("name=TurismBD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AtractieTuristica> AtractieTuristicas { get; set; }
        public virtual DbSet<Camera> Cameras { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Comanda> Comandas { get; set; }
        public virtual DbSet<Comentariu> Comentarius { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Itinerariu> Itinerarius { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<OfertaSejur> OfertaSejurs { get; set; }
        public virtual DbSet<Ora> Oras { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tara> Taras { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
