//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turism
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfertaSejur
    {
        public OfertaSejur()
        {
            this.Comandas = new HashSet<Comanda>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdTara { get; set; }
        public Nullable<int> NrPersoane { get; set; }
        public Nullable<int> IdHotel { get; set; }
        public Nullable<System.DateTime> DataInceput { get; set; }
        public Nullable<System.DateTime> DataSfarsit { get; set; }
        public Nullable<double> Pret { get; set; }
        public Nullable<bool> AllInclusive { get; set; }
        public Nullable<bool> InCurs { get; set; }
    
        public virtual ICollection<Comanda> Comandas { get; set; }
        public virtual Tara Tara { get; set; }
    }
}
