//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turism
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ora
    {
        public Ora()
        {
            this.AtractieTuristicas = new HashSet<AtractieTuristica>();
        }
    
        public int ID { get; set; }
        public string Denumire { get; set; }
        public Nullable<int> IdTara { get; set; }
        public Nullable<bool> EsteCapitala { get; set; }
        public Nullable<double> Latitudine { get; set; }
        public Nullable<double> Longitudine { get; set; }
    
        public virtual ICollection<AtractieTuristica> AtractieTuristicas { get; set; }
        public virtual Tara Tara { get; set; }
    }
}
